Exploratory Data Analysis

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy

phot_data = pd.read_csv("string_phot_rat_data.csv")

In [3]:
phot_data.head()

,rat,percentage_x,x_pos_centered,y_pos_centered,x_reach_centered,y_reach_centered,df_centered,effort_centered,rot_centered,paw_vel_centered
0,5,0.00,0.566854,1.080798,0.566854,1.080798,-0.007717,0.033047,-9.731920,4.518823
1,5,0.01,0.407729,1.067616,0.407729,1.067616,-0.006712,0.028269,-9.729127,2.845532
2,5,0.02,0.271484,1.024612,0.271484,1.024612,-0.006235,0.030529,-9.726279,1.519936
3,5,0.03,0.169633,0.956670,0.169633,0.956670,-0.012567,0.040871,-9.723376,0.318620
4,5,0.04,0.095008,0.873968,0.095008,0.873968,-0.010752,0.029611,-9.720413,-0.967590

In [14]:
data = phot_data.drop(columns=['percentage_x', 'x_reach_centered', 'y_reach_centered'])
data = data.dropna()

In [15]:
data.head()

,rat,x_pos_centered,y_pos_centered,df_centered,effort_centered,rot_centered,paw_vel_centered
0,5,0.566854,1.080798,-0.007717,0.033047,-9.731920,4.518823
1,5,0.407729,1.067616,-0.006712,0.028269,-9.729127,2.845532
2,5,0.271484,1.024612,-0.006235,0.030529,-9.726279,1.519936
3,5,0.169633,0.956670,-0.012567,0.040871,-9.723376,0.318620
4,5,0.095008,0.873968,-0.010752,0.029611,-9.720413,-0.967590

In [16]:
data['rat'].unique()

array([ 5,  6, 25])

In [ ]:
# one hot encode rat
rat6 = data['rat'] == 6
rat25 = data['rat'] == 25
data['rat6'] = rat6.astype(int)
data['rat25'] = rat25.astype(int)